node {
    stage('SCM Checkount'){
      git 'https://github.com/SAMIMES/divers'
    }
    stage('Compile-Package'){
       //Get Maven home Path
     def mvnhome = tool name: 'maven 3', type: 'maven'
        "${mvnhome}/bin/mvn install package"
    }
}
